  
version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=users
      - DB_CONNECTION=mongodb://futureproof:userpass@db:27017
      - PORT= 3000
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: mongo:4-focal
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=futureproof
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_PASSWORD=userpass
volumes:
  dbdata:
